USE fitnessDemo;
DROP TABLE IF EXISTS ExerciseWorkoutLinks;
DROP TABLE IF EXISTS Goals;
DROP TABLE IF EXISTS Exercises;
DROP TABLE IF EXISTS Workouts;
DROP TABLE IF EXISTS Users;

DROP VIEW IF EXISTS FullLinkView;

DROP DATABASE IF EXISTS fitnessDemo;